branch-defaults:
  default:
    environment: SocketShot-Prod-env
environment-defaults:
  SocketShot-Prod-env:
    branch: null
    repository: null
global:
  application_name: SocketShot-App
  branch: null
  default_ec2_keyname: DriveKeyPairOhio
  default_platform: Node.js 22 running on 64bit Amazon Linux 2
  default_region: us-east-2
  environment: SocketShot-Prod-env
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
